package de.ma_vin.ape.users.controller.auth;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response of authorization requests
 * See also <a>https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2</a>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AuthorizationResponse {
    /**
     * REQUIRED.  The authorization code generated by the authorization server.
     * The authorization code MUST expire shortly after it is issued to mitigate the risk of leaks.
     * A maximum authorization code lifetime of 10 minutes is RECOMMENDED.
     * The client MUST NOT use the authorization code more than once.
     * If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code.
     * The authorization code is bound to the client identifier and redirection URI.
     */
    private String code;

    /**
     * REQUIRED if the "state" parameter was present in the client authorization request.
     * The exact value received from the client.
     */
    private String state;

}
