spring:
  datasource:
    url: jdbc:h2:mem:mvapeuser
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: https://localhost:8443/oauth/introspection
          introspection-client-id: users
          introspection-client-secret: f58497fe32e68138273588d18f62d92366a97bb451d573fb1860ce615e540e15
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: target/keystore/keystore.p12
    key-store-password: changeit
    key-alias: users
    protocol: TLS
    enabled-protocols: TLSv1.3
logging:
  level:
    root: INFO
db:
  user:
    isToInitialize: true
    isCommonGroupToInitialize: true
    initUserWithDefaultPwd: false
tokenSecret: SomeSecret
tokenExpiresInSeconds: 300
refreshTokenExpiresInSeconds: 900
encodingAlgorithm: HS256
authorizeCodeExpiresInSeconds: 600
auth:
  tokenWithClientSecret: false
  clients:
    - clientId: users
      secret: f58497fe32e68138273588d18f62d92366a97bb451d573fb1860ce615e540e15
      url: https://localhost:8443
      redirects:
        - redirect-start: https://localhost:8443/
    - clientId: ape.user.ui
      secret: changeIt
      url: https://localhost:4200
      redirects:
        - redirect-start: https://localhost:4200/