spring:
  datasource:
    url: jdbc:h2:mem:mvapeuser
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8080/oauth/introspection
          introspection-client-id: users
          introspection-client-secret: f58497fe32e68138273588d18f62d92366a97bb451d573fb1860ce615e540e15
logging:
  level:
    root: INFO
db:
  user:
    isToInitialize: true
    isCommonGroupToInitialize: true
    initUserWithDefaultPwd: false
tokenSecret: SomeSecret
tokenExpiresInSeconds: 300
refreshTokenExpiresInSeconds: 900
encodingAlgorithm: HS256
authorizeCodeExpiresInSeconds: 600
auth:
  tokenWithClientSecret: false
  clients:
    - clientId: users
      secret: f58497fe32e68138273588d18f62d92366a97bb451d573fb1860ce615e540e15
      url: http://localhost:8080
      redirects:
        - redirect-start: http://localhost:8080/
    - clientId: ape.user.ui
      secret: changeIt
      url: http://localhost:4200
      redirects:
        - redirect-start: http://localhost:4200/