name: Build and analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'master'

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'master' )

    runs-on: ubuntu-latest

    steps:
      - name: Checkout users
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout maven settings
        uses: actions/checkout@v3
        with:
          repository: Ma-Vin/de.ma_vin.maven
          token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          path: maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          java-package: jdk
          cache: 'maven'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
      - name: Build and analyze users
        env:
          GITHUB_PACKAGES_USERNAME: ${{ secrets.APE_GITHUB_PACKAGES_USER }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.APE_GITHUB_PACKAGES_PAT }}
          GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: > 
          mvn -B clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -P sonar-cloud,gen-model
          --file main/pom.xml
          --settings maven/settings.xml
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2