name: Build and analyze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout users
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout maven settings
        uses: actions/checkout@v2
        with:
          repository: Ma-Vin/de.ma_vin.maven
          token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          path: maven
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
      - name: Build and analyze users
        env:
          GITHUB_PACKAGES_USERNAME: ${{ secrets.APE_GITHUB_PACKAGES_USER }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.APE_GITHUB_PACKAGES_PAT }}
          GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P sonar-cloud,gen-model --file main/pom.xml --settings maven/settings.xml
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1